/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1;

import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

/**
 *
 * @author mgsr1
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());
    private final ManejoArchivos manejo = new ManejoArchivos();
    private Grafo grafo;
    private Grafo grafoBase;
    private Graph grafoVisual;
    private SwingViewer viewer;
    private ViewPanel viewPanel;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCargar = new javax.swing.JToggleButton();
        btnGuardar = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btnAgregarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnAgregarRelación = new javax.swing.JButton();
        btnCfc = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usertoinsert = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        connectionsender = new javax.swing.JTextField();
        connectionreceiver = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        btnCargar.setText("Cargar Archivo");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        btnGuardar.setText("Actualizar Repositorio");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        btnReiniciar.setText("Reiniciar Grafo");
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        btnAgregarUsuario.setText("Agregar");
        btnAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        btnAgregarRelación.setText("Agregar Relación");
        btnAgregarRelación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRelaciónActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarRelación, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        btnCfc.setText("Mostrar CFC Kosaraju");
        getContentPane().add(btnCfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));
        getContentPane().add(usertoinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel2.setText("De:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel3.setText("A:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));
        getContentPane().add(connectionsender, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));
        getContentPane().add(connectionreceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        this.grafo = this.manejo.subir_archivo();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void btnAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUsuarioActionPerformed
        if(this.grafo == null){
            this.grafo.insertar(this.usertoinsert.getText());
        }else{
            JOptionPane.showMessageDialog(null, "No se ha subido un archivo para crear el grafo");
        }
    }//GEN-LAST:event_btnAgregarUsuarioActionPerformed

    private void btnAgregarRelaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRelaciónActionPerformed
        if(this.grafo == null){
            NodoGrafo aux = new NodoGrafo("");
            aux = this.grafo.Buscar(this.connectionsender.getText());
            aux.minilista.insertar_nueva(this.connectionreceiver.getText());
        }else{
            JOptionPane.showMessageDialog(null, "No se ha subido un archivo para crear el grafo");
        }
    }//GEN-LAST:event_btnAgregarRelaciónActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        if(this.grafo == null){
            this.grafo.Eliminar(this.grafo.Buscar(this.usertoinsert.getText()));
            this.grafo.eliminarconexiones(this.usertoinsert.getText());
        }else{
            JOptionPane.showMessageDialog(null, "No se ha subido un archivo para crear el grafo");
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(this.grafo == null){
            this.manejo.actualizar_archivo(this.grafo);
        }else{
            JOptionPane.showMessageDialog(null, "No se ha subido un archivo para crear el grafo");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRelación;
    private javax.swing.JButton btnAgregarUsuario;
    private javax.swing.JToggleButton btnCargar;
    private javax.swing.JButton btnCfc;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JTextField connectionreceiver;
    private javax.swing.JTextField connectionsender;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usertoinsert;
    // End of variables declaration//GEN-END:variables
}
